milestone_controllers:
    type: attribute
    resource:
        path: ../src/Milestone/Presentation/Http/Controller/
        namespace: App\Milestone\Presentation\Http\Controller
    requirements:
        milestoneId: '\d+'
        fileId: '[a-zA-Z0-9]+'
